<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="connecter.css">

    <title>Document</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark" >
        <a class="navbar-brand" href="accueil.html">RAFood</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav">
            <li class="nav-item active">
              <a class="nav-link" href="#">Inscription <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Menu</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Votre commande</a>
            </li>
          </ul>
         
        </div> 
     </nav> 
    <h3>Connecter</h3>
    <div class="jumbotron">
     <form action="connecter.php"  method="POST">
     
     <div class="form-group">
               <label for="exampleInputEmail1">Name:</label>
               <input type="text" class="form-control" id="username"  placeholder="Entrer Votre Nom" name="username">
               <span class="text-danger"><?php if (isset($username_error)) echo $username_error?></span>
              </div>
            
             <div class="form-group">
                     <label for="exampleInputEmail1">password</label>
                     <input type="password" class="form-control" id="pwd"  placeholder="password" name="pass">
                     <span class="text-danger"><?php if (isset($pass_error)) echo $pass_error?></span>
                    </div>
    
             <div class="col-md-6">
                        <button type="submit" name="login" class="btn btn-block btn-outline-primary">Enregistrer</button>
                    </div>
   
    
    
    </form>
    </div>
    <footer class="ft"> Copyright AZIZ  RYMAET</footer>
</body>
</html>